/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.interpss.editor.doc.validation;

import org.interpss.editor.jgraph.ui.app.IAppSimuContext;


/**
 * A sample validator interface for {@link org.interpss.editor.doc.IpssSimuDocument}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IpssSimuDocumentValidator {
	boolean validate();

	boolean validateAppSimuCtx(IAppSimuContext value);

}
