/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.interpss.editor.ws.validation;

import org.interpss.editor.ws.WsItemInitStatus;


/**
 * A sample validator interface for {@link org.interpss.editor.ws.IpssProjectItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IpssProjectItemValidator {
	boolean validate();

	boolean validateIntStatus(WsItemInitStatus value);

}
