/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.load.validation;

import org.opencim.cim.iec61970.wire.EnergyConsumer;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.load.NonConformLoadSchedule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NonConformLoadScheduleValidator {
	boolean validate();

	boolean validateEnergyConsumer(EnergyConsumer value);
}
