package org.interpss.editor.ui.edit.trans.branch;
  
/**
 *
 */
import java.util.Vector;

import javax.swing.JDialog;

import com.interpss.common.util.IpssLogger;
import com.interpss.editor.jgraph.ui.edit.IFormDataPanel;
 
public class NBAclfTransBranchEditPanel extends javax.swing.JPanel implements IFormDataPanel {
	private static final long serialVersionUID = 1;
	private JDialog parent = null;

    private NBBranchPositivePanel _branchPositivePanel = new NBBranchPositivePanel();
    
	public void initPanel(JDialog aParent) {
		parent = aParent;
		_branchPositivePanel.initPanel(parent);	
		this.add(_branchPositivePanel);
	}
    
	public void init(Object netContainer, Object form) {
		IpssLogger.getLogger().info("NBAclfTransBranchEditPanel init() called");
		
	   _branchPositivePanel.init(netContainer, form);
	}
	
    public boolean setForm2Editor() {
		IpssLogger.getLogger().info("NBAclfTransBranchEditPanel setForm2Edtior() called");
		_branchPositivePanel.setForm2Editor();
    	return true;
	}
    
    public boolean saveEditor2Form(Vector errMsg) throws Exception {
		IpssLogger.getLogger().info("NBAclfTransBranchEditPanel saveEditor2Form() called");
		return _branchPositivePanel.saveEditor2Form(errMsg);
    }
    
    /** Creates new form AclfEditPanel */
    public NBAclfTransBranchEditPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
