 package org.interpss.editor.ui.edit.trans.branch;
  
/**
 *
 */
import java.util.Vector;

import javax.swing.JDialog;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.interpss.editor.form.GFormContainer;
import org.interpss.editor.form.GNetForm;

import com.interpss.common.util.IpssLogger;
import com.interpss.editor.jgraph.ui.edit.IFormDataPanel;
 
 
public class NBAcscTransBranchEditPanel extends javax.swing.JPanel implements IFormDataPanel {
	private static final long serialVersionUID = 1;
	private JDialog parent = null;

    private GFormContainer _netContainer = null;
    
    private NBBranchPositivePanel _positiveEditPanel = new NBBranchPositivePanel();
    private NBBranchScDataPanel       _scEditPanel = new NBBranchScDataPanel();
    
	public void initPanel(JDialog aParent) {
		parent = aParent;
		_positiveEditPanel.initPanel(parent);
		_scEditPanel.initPanel(parent);
    	scInfoEditPanel.add(_scEditPanel);
	    
	    branchInfoEditTabbedPane.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent e) {
				if (branchInfoEditTabbedPane.getSelectedIndex() == 0) {
					IpssLogger.getLogger().info("Loadflow Info Tab selected");
					try {
						Vector errMsg = new Vector();
						_scEditPanel.saveEditor2Form(errMsg);
					} catch (Exception exc) {}	
				    _positiveEditPanel.setForm2Editor();
				}
				else if (branchInfoEditTabbedPane.getSelectedIndex() == 1) {
					IpssLogger.getLogger().info("Short Circut Info Tab selected");
					try {
						Vector errMsg = new Vector();
						_positiveEditPanel.saveEditor2Form(errMsg);
					} catch (Exception exc) {}	
				    _scEditPanel.setForm2Editor();
				}
			}});
	}
    
	public void init(Object netContainer, Object form) {
		IpssLogger.getLogger().info("AcscTransBranchEditPanel init() called");
		_netContainer = (GFormContainer)netContainer;
		
    	if (((GNetForm)((GFormContainer)netContainer).getGNetForm()).getAcscNetData().isHasAclfData()) {
	    	branchInfoEditTabbedPane.setEnabledAt(0, true);
	    	lfInfoEditPanel.add(_positiveEditPanel);
		    _positiveEditPanel.init(netContainer, form);
	    }
	    else {
	    	branchInfoEditTabbedPane.setEnabledAt(0, false);
	    }
    	
	    _scEditPanel.init(netContainer, form);
	}
	
    public boolean setForm2Editor() {
		IpssLogger.getLogger().info("AcscTransBranchEditPanel setForm2Editor() called");
	    if (((GNetForm)_netContainer.getGNetForm()).getAcscNetData().isHasAclfData() ) {
			_positiveEditPanel.setForm2Editor();
	    }
	    
		_scEditPanel.setForm2Editor();

		return true;
	}
    
    public boolean saveEditor2Form(Vector errMsg) throws Exception {
		IpssLogger.getLogger().info("AcscTransBranchEditPanel saveEditor2Form() called");
		boolean ok = true;

	    if (((GNetForm)_netContainer.getGNetForm()).getAcscNetData().isHasAclfData() ) {
		    if (!_positiveEditPanel.saveEditor2Form(errMsg))
		    	ok = false;
	    }

	    if (!_scEditPanel.saveEditor2Form(errMsg))
	    	ok = false;

	    return ok;
    }
    
    /** Creates new form AclfEditPanel */
    public NBAcscTransBranchEditPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        branchInfoEditTabbedPane = new javax.swing.JTabbedPane();
        lfInfoEditPanel = new javax.swing.JPanel();
        scInfoEditPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        branchInfoEditTabbedPane.setName("branchInfoEditTabbedPane");
        branchInfoEditTabbedPane.addTab("Loadflow", lfInfoEditPanel);

        branchInfoEditTabbedPane.addTab("Short Circuit", scInfoEditPanel);

        branchInfoEditTabbedPane.setSelectedIndex(1);

        add(branchInfoEditTabbedPane, java.awt.BorderLayout.CENTER);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane branchInfoEditTabbedPane;
    private javax.swing.JPanel lfInfoEditPanel;
    private javax.swing.JPanel scInfoEditPanel;
    // End of variables declaration//GEN-END:variables
}	
