/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.datatype.string.CompositeSwitchType;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.CompositeSwitch}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CompositeSwitchValidator {
	boolean validate();

	boolean validateCompositeSwitchType(CompositeSwitchType value);
	boolean validateSwitches(EList value);
}
