/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.datatype.real.Reactance;
import org.opencim.datatype.real.Resistance;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.RegulationSchedule}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RegulationScheduleValidator {
	boolean validate();

	boolean validateLineDropCompensation(Boolean value);
	boolean validateLineDropR(Resistance value);
	boolean validateLineDropX(Reactance value);
	boolean validateVoltageControlZones(EList value);
	boolean validateRegulatingCondEqs(EList value);
	boolean validateTapChangers(EList value);
}
