/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.opencim.datatype.real.Reactance;
import org.opencim.datatype.real.Voltage;
import org.opencim.datatype.real.VoltagePerReactivePower;

import org.opencim.datatype.string.ControlMode;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.StaticVarCompensator}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StaticVarCompensatorValidator {
	boolean validate();

	boolean validateCapacitiveRating(Reactance value);
	boolean validateInductiveRating(Reactance value);
	boolean validateSVCControlMode(ControlMode value);
	boolean validateSlope(VoltagePerReactivePower value);
	boolean validateVoltageSetPoint(Voltage value);
}
