/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.opencim.cim.iec61970.wire.ConductorType;
import org.opencim.cim.iec61970.wire.WireType;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.WireArrangement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WireArrangementValidator {
	boolean validate();

	boolean validateMountingPointX(Integer value);
	boolean validateMountingPointY(Integer value);
	boolean validateConductorType(ConductorType value);
	boolean validateWireType(WireType value);
}
