 /*
  * @(#)NBDStabTransBranchEditPanel.java   
  *
  * Copyright (C) 2006 www.interpss.org
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU LESSER GENERAL PUBLIC LICENSE
  * as published by the Free Software Foundation; either version 2.1
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * @Author Mike Zhou
  * @Version 1.0
  * @Date 09/15/2006
  * 
  *   Revision History
  *   ================
  *
  */

package org.interpss.editor.ui.edit.trans.branch;
  
import java.util.Vector;

import javax.swing.JDialog;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

import org.interpss.editor.jgraph.ui.edit.IFormDataPanel;

import com.interpss.common.util.IpssLogger;
 
 
public class NBDStabTransBranchEditPanel extends javax.swing.JPanel implements IFormDataPanel {
	private static final long serialVersionUID = 1;
	private JDialog parent = null;

    private NBBranchPositivePanel _positiveEditPanel = new NBBranchPositivePanel();
    private NBBranchScDataPanel   _scEditPanel = new NBBranchScDataPanel();
    
	public void initPanel(JDialog aParent) {
		parent = aParent;
		_positiveEditPanel.initPanel(parent);
		_positiveEditPanel.disableScripting();
		_scEditPanel.initPanel(parent, this);
		_scEditPanel.disableScripting();
    	scInfoEditPanel.add(_scEditPanel);
	    
	    branchInfoEditTabbedPane.addChangeListener(new ChangeListener() {
			public void stateChanged(ChangeEvent e) {
				if (branchInfoEditTabbedPane.getSelectedIndex() == 0) {
					IpssLogger.getLogger().info("Loadflow Info Tab selected");
					try {
						Vector<String> errMsg = new Vector<String>();
						_scEditPanel.saveEditor2Form(errMsg);
					} catch (Exception exc) {}	
				    _positiveEditPanel.setForm2Editor();
				}
				else if (branchInfoEditTabbedPane.getSelectedIndex() == 1) {
					IpssLogger.getLogger().info("Short Circut Info Tab selected");
					try {
						Vector<String> errMsg = new Vector<String>();
						_positiveEditPanel.saveEditor2Form(errMsg);
					} catch (Exception exc) {}	
				    _scEditPanel.setForm2Editor();
				}
			}});
	}
    
	public void init(Object netContainer, Object form) {
		IpssLogger.getLogger().info("DStabTransBranchEditPanel init() called");
		
    	branchInfoEditTabbedPane.setEnabledAt(0, true);
    	lfInfoEditPanel.add(_positiveEditPanel);
	    _positiveEditPanel.init(netContainer, form);
    	
	    _scEditPanel.init(netContainer, form);

	    // Branch device scripting not implemented yet
	    branchInfoEditTabbedPane.setEnabledAt(2, false);
	    scriptingCheckBox.setEnabled(false);
	}
	
    public boolean setForm2Editor() {
		IpssLogger.getLogger().info("DStabTransBranchEditPanel setForm2Editor() called");
		_positiveEditPanel.setForm2Editor();
	    
		_scEditPanel.setForm2Editor();

		return true;
	}
    
    public boolean saveEditor2Form(Vector<String> errMsg) throws Exception {
		IpssLogger.getLogger().info("DStabTransBranchEditPanel saveEditor2Form() called");

	    _positiveEditPanel.saveEditor2Form(errMsg);

	    _scEditPanel.saveEditor2Form(errMsg);

	    return errMsg.size() == 0;
    }
    
    /** Creates new form AclfEditPanel */
    public NBDStabTransBranchEditPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        branchInfoEditTabbedPane = new javax.swing.JTabbedPane();
        lfInfoEditPanel = new javax.swing.JPanel();
        scInfoEditPanel = new javax.swing.JPanel();
        scriptPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        scriptCheckPanel = new javax.swing.JPanel();
        scriptingCheckBox = new javax.swing.JCheckBox();

        setLayout(new java.awt.BorderLayout());

        branchInfoEditTabbedPane.setFont(new java.awt.Font("Dialog", 0, 12));
        branchInfoEditTabbedPane.setName("branchInfoEditTabbedPane"); // NOI18N
        branchInfoEditTabbedPane.addTab("Branch Info(+)", lfInfoEditPanel);
        branchInfoEditTabbedPane.addTab("Branch Info(+/-/0)", scInfoEditPanel);

        jTextArea1.setColumns(80);
        jTextArea1.setFont(new java.awt.Font("Courier New", 0, 12));
        jTextArea1.setRows(30);
        jTextArea1.setTabSize(3);
        jScrollPane1.setViewportView(jTextArea1);

        scriptPanel.add(jScrollPane1);

        branchInfoEditTabbedPane.addTab("Branch Device Scripting", scriptPanel);

        branchInfoEditTabbedPane.setSelectedIndex(1);

        add(branchInfoEditTabbedPane, java.awt.BorderLayout.CENTER);

        scriptingCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        scriptingCheckBox.setText("Dynamic Branch Device Scripting");
        scriptingCheckBox.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        scriptingCheckBox.setMargin(new java.awt.Insets(0, 0, 0, 0));
        scriptingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scriptingCheckBoxActionPerformed(evt);
            }
        });
        scriptCheckPanel.add(scriptingCheckBox);

        add(scriptCheckPanel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    private void scriptingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scriptingCheckBoxActionPerformed
    // TODO add your handling code here:
}//GEN-LAST:event_scriptingCheckBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane branchInfoEditTabbedPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel lfInfoEditPanel;
    private javax.swing.JPanel scInfoEditPanel;
    private javax.swing.JPanel scriptCheckPanel;
    private javax.swing.JPanel scriptPanel;
    private javax.swing.JCheckBox scriptingCheckBox;
    // End of variables declaration//GEN-END:variables
}	
