DROP TABLE DSTAB_SIMURECORD;
DROP TABLE STUDYCASE;
DROP TABLE IPSSCASE;
DROP TABLE IPSSPROJECT;
DROP TABLE SIMURECORDTYPE;

CREATE TABLE DBMETADATA ( 
  SCHEMA_VERSION	VARCHAR(24) NOT NULL
); 

INSERT INTO DBMETADATA (SCHEMA_VERSION) VALUES('1.00.00');

CREATE TABLE SIMURECORDTYPE ( 
  ID	   INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  NAME     VARCHAR(24) NOT NULL,
  CONSTRAINT SIMURECORDTYPE_UNIQUE UNIQUE (NAME),
  PRIMARY KEY (ID)
); 

INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabMachineStates');
INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabExcStates');
INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabGovStates');
INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabPssStates');
INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabBusStates');

INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabScripDBusStates');
INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabDynamicLoadStates');
INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabSVCStates');
INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabFACSTStates');
INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabRelayStates');
INSERT INTO SIMURECORDTYPE (NAME) VALUES('DStabScripDBranchStates');


CREATE TABLE IPSSPROJECT ( 
  ID	     INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PROJ_NAME  VARCHAR(64) NOT NULL,
  PROJ_DESC  VARCHAR(512) NOT NULL,
  WORKSPACE_PATH  VARCHAR(256) NOT NULL,
  FILE_PATH  VARCHAR(256) NOT NULL,
  CREATE_TIME TIMESTAMP NOT NULL,
  UPDATE_TIME TIMESTAMP NOT NULL,
  CONSTRAINT IPSSPROJECT_PROJNAME_UNIQUE UNIQUE (PROJ_NAME, WORKSPACE_PATH),
  PRIMARY KEY (ID)
);

CREATE TABLE IPSSCASE ( 
  ID	     INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  PROJ_ID    INT NOT NULL,
  CASE_NAME  VARCHAR(256) NOT NULL,
  TIME_STAMP TIMESTAMP NOT NULL,
  CONSTRAINT IPSSCASE_CASENAME_UNIQUE UNIQUE (PROJ_ID, CASE_NAME),
  CONSTRAINT IPSSCASE_PROJ_ID_FK FOREIGN KEY  (PROJ_ID) REFERENCES IPSSPROJECT (ID),
  PRIMARY KEY (ID)
); 

CREATE TABLE STUDYCASE ( 
  CASE_ID	  INT NOT NULL,
  PROJ_ID	  INT NOT NULL,
  CASETYPE	  VARCHAR(24) NOT NULL,
  DATA_STR    LONG VARCHAR NOT NULL,
  CONSTRAINT STUDYCASE_CASEID_FK FOREIGN KEY  (CASE_ID) REFERENCES IPSSCASE (ID),
  CONSTRAINT STUDYCASE_PROJID_FK FOREIGN KEY  (PROJ_ID) REFERENCES IPSSPROJECT (ID)
); 

CREATE TABLE DSTAB_SIMURECORD ( 
  ID	        INT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  RECTYPE_ID	INT NOT NULL,
  CASE_ID	    INT NOT NULL,
  ELEM_ID_STR   VARCHAR(24) NOT NULL,
  SIMU_TIME     DOUBLE NOT NULL,
  SIMU_REC      LONG VARCHAR NOT NULL,
  CONSTRAINT DSATB_SIMURECORD_RECTYPEID_FK FOREIGN KEY  (RECTYPE_ID) REFERENCES SIMURECORDTYPE (ID), 
  CONSTRAINT DSATB_SIMURECORD_CASEID_FK FOREIGN KEY  (CASE_ID) REFERENCES IPSSCASE (ID),
  PRIMARY KEY (ID)
); 

INSERT INTO IPSSPROJECT (PROJ_NAME,PROJ_DESC,WORKSPACE_PATH,FILE_PATH,CREATE_TIME,UPDATE_TIME) VALUES('ProjName', 'Desc', 'WorkspacePath', 'FilePath', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO IPSSPROJECT (PROJ_NAME,PROJ_DESC,WORKSPACE_PATH,FILE_PATH,CREATE_TIME,UPDATE_TIME) VALUES('ProjName1', 'Desc', 'WorkspacePath', 'FilePath', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO IPSSCASE (PROJ_ID,CASE_NAME,TIME_STAMP) VALUES(1,'CaseName', CURRENT_TIMESTAMP);
INSERT INTO STUDYCASE (CASE_ID,PROJ_ID,CASETYPE,DATA_STR) VALUES(1,1,'AclfType','DataStr');


INSERT INTO DSTAB_SIMURECORD (RECTYPE_ID,CASE_ID,ELEM_ID_STR,SIMU_TIME,SIMU_REC) VALUES(1,1,'ElemId',0.0,'SimuRecStr');
INSERT INTO DSTAB_SIMURECORD (RECTYPE_ID,CASE_ID,ELEM_ID_STR,SIMU_TIME,SIMU_REC) VALUES(1,1,'ElemId',0.1,'SimuRecStr');

