/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.core.validation;

import org.opencim.cim.iec61970.core.CurveSchedule;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.core.CurveSchedData}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CurveSchedDataValidator {
	boolean validate();

	boolean validateRampData(Object value);
	boolean validateRampDataValue(Object value);
	boolean validateXAxisData(Object value);
	boolean validateY1AxisData(Object value);
	boolean validateY2AxisData(Object value);
	boolean validateCurveSchedule(CurveSchedule value);
}
