/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.core.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.cim.iec61970.core.SubControlArea;

import org.opencim.cim.iec61970.load.LoadArea;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.core.Substation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SubstationValidator {
	boolean validate();

	boolean validateSubControlArea(SubControlArea value);
	boolean validateLoadArea(LoadArea value);
	boolean validateVoltageLevels(EList value);
	boolean validateBays(EList value);
	boolean validateContains_CompositeSwitches(EList value);
}
