/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.core.validation;

import org.opencim.cim.iec61970.core.ConductingEquipment;

import org.opencim.cim.iec61970.topology.ConnectivityNode;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.core.Terminal}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TerminalValidator {
	boolean validate();

	boolean validateConductingEquipment(ConductingEquipment value);
	boolean validateConnectivityNode(ConnectivityNode value);
}
