/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.core.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.cim.iec61970.core.BaseVoltage;
import org.opencim.cim.iec61970.core.Substation;

import org.opencim.datatype.real.Voltage;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.core.VoltageLevel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VoltageLevelValidator {
	boolean validate();

	boolean validateHighVoltageLimit(Voltage value);
	boolean validateLowVoltageLimit(Voltage value);
	boolean validateSubstation(Substation value);
	boolean validateBays(EList value);
	boolean validateBaseVoltage(BaseVoltage value);
}
