/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.cim.iec61970.core.BasePower;

/**
 * A sample validator interface for {@link org.opencim.cim.SimulationModel}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SimulationModelValidator {
	boolean validate();

	boolean validateBasePower(BasePower value);
	boolean validateCompanies(EList value);
	boolean validateTopologicalIslands(EList value);
	boolean validatePsResources(EList value);
}
