/*
 * NBDStabDisplay.java
 *
 * Created on January 1, 2007, 7:17 PM
 */

package org.interpss.editor.ui.output;

/**
 *
 * @author  mzhou
 */
public class NBDStabDisplay extends javax.swing.JFrame {
    
    /** Creates new form NBDStabDisplay */
    public NBDStabDisplay() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        typeSelectButtonGroup = new javax.swing.ButtonGroup();
        typeSelectPanel = new javax.swing.JPanel();
        allRadioButton = new javax.swing.JRadioButton();
        machRadioButton = new javax.swing.JRadioButton();
        busRadioButton = new javax.swing.JRadioButton();
        busDeviceRadioButton = new javax.swing.JRadioButton();
        branchRadioButton = new javax.swing.JRadioButton();
        branchDeviceRadioButton = new javax.swing.JRadioButton();
        itemSelectPanel = new javax.swing.JPanel();
        itemSelectScrollPane = new javax.swing.JScrollPane();
        netItemList = new javax.swing.JList();
        stateSelectScrollPane = new javax.swing.JScrollPane();
        stateItemList = new javax.swing.JList();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transient Stability Simulation Diaplay");
        typeSelectButtonGroup.add(allRadioButton);
        allRadioButton.setText("All");
        allRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        allRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        allRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allRadioButtonActionPerformed(evt);
            }
        });

        typeSelectButtonGroup.add(machRadioButton);
        machRadioButton.setText("Machine");
        machRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        machRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        machRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machRadioButtonActionPerformed(evt);
            }
        });

        typeSelectButtonGroup.add(busRadioButton);
        busRadioButton.setText("Bus");
        busRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        busRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        busRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busRadioButtonActionPerformed(evt);
            }
        });

        typeSelectButtonGroup.add(busDeviceRadioButton);
        busDeviceRadioButton.setText("Dynamic Bus Device");
        busDeviceRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        busDeviceRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        busDeviceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busDeviceRadioButtonActionPerformed(evt);
            }
        });

        typeSelectButtonGroup.add(branchRadioButton);
        branchRadioButton.setText("Branch");
        branchRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        branchRadioButton.setEnabled(false);
        branchRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        branchRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchRadioButtonActionPerformed(evt);
            }
        });

        typeSelectButtonGroup.add(branchDeviceRadioButton);
        branchDeviceRadioButton.setText("Dynamic Branch Deveice");
        branchDeviceRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        branchDeviceRadioButton.setEnabled(false);
        branchDeviceRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        branchDeviceRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchDeviceRadioButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout typeSelectPanelLayout = new org.jdesktop.layout.GroupLayout(typeSelectPanel);
        typeSelectPanel.setLayout(typeSelectPanelLayout);
        typeSelectPanelLayout.setHorizontalGroup(
            typeSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(typeSelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(allRadioButton)
                .add(20, 20, 20)
                .add(machRadioButton)
                .add(19, 19, 19)
                .add(busRadioButton)
                .add(18, 18, 18)
                .add(busDeviceRadioButton)
                .add(20, 20, 20)
                .add(branchRadioButton)
                .add(16, 16, 16)
                .add(branchDeviceRadioButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        typeSelectPanelLayout.setVerticalGroup(
            typeSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(typeSelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(typeSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(allRadioButton)
                    .add(machRadioButton)
                    .add(busRadioButton)
                    .add(busDeviceRadioButton)
                    .add(branchRadioButton)
                    .add(branchDeviceRadioButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        netItemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        netItemList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                netItemListMouseClicked(evt);
            }
        });

        itemSelectScrollPane.setViewportView(netItemList);

        stateItemList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        stateItemList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stateItemListMouseClicked(evt);
            }
        });

        stateSelectScrollPane.setViewportView(stateItemList);

        org.jdesktop.layout.GroupLayout itemSelectPanelLayout = new org.jdesktop.layout.GroupLayout(itemSelectPanel);
        itemSelectPanel.setLayout(itemSelectPanelLayout);
        itemSelectPanelLayout.setHorizontalGroup(
            itemSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(itemSelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(itemSelectScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 56, Short.MAX_VALUE)
                .add(stateSelectScrollPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 292, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        itemSelectPanelLayout.setVerticalGroup(
            itemSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(itemSelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(itemSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(stateSelectScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .add(itemSelectScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE))
                .addContainerGap())
        );

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(typeSelectPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(41, 41, 41)
                        .add(itemSelectPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(250, 250, 250)
                        .add(closeButton)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(24, 24, 24)
                .add(typeSelectPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(itemSelectPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(closeButton)
                .add(15, 15, 15))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_closeButtonActionPerformed

    private void stateItemListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stateItemListMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_stateItemListMouseClicked

    private void netItemListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_netItemListMouseClicked
// TODO add your handling code here:
    }//GEN-LAST:event_netItemListMouseClicked

    private void branchDeviceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchDeviceRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_branchDeviceRadioButtonActionPerformed

    private void branchRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_branchRadioButtonActionPerformed

    private void busDeviceRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busDeviceRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_busDeviceRadioButtonActionPerformed

    private void busRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_busRadioButtonActionPerformed

    private void machRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_machRadioButtonActionPerformed

    private void allRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_allRadioButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NBDStabDisplay().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allRadioButton;
    private javax.swing.JRadioButton branchDeviceRadioButton;
    private javax.swing.JRadioButton branchRadioButton;
    private javax.swing.JRadioButton busDeviceRadioButton;
    private javax.swing.JRadioButton busRadioButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JPanel itemSelectPanel;
    private javax.swing.JScrollPane itemSelectScrollPane;
    private javax.swing.JRadioButton machRadioButton;
    private javax.swing.JList netItemList;
    private javax.swing.JList stateItemList;
    private javax.swing.JScrollPane stateSelectScrollPane;
    private javax.swing.ButtonGroup typeSelectButtonGroup;
    private javax.swing.JPanel typeSelectPanel;
    // End of variables declaration//GEN-END:variables
    
}
