/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.interpss.model.editor.appSimu.validation;

import org.interpss.model.editor.appSimu.ProjectData;
import org.interpss.model.editor.appSimu.SimuRunType;

/**
 * A sample validator interface for {@link org.interpss.model.editor.appSimu.AppSimuContext}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AppSimuContextValidator {
	boolean validate();

	boolean validateLastSimuRunType(SimuRunType value);
	boolean validateAclfConverged(boolean value);
	boolean validateScCalculated(boolean value);
	boolean validateProjData(ProjectData value);
	boolean validateSimuCtx(Object value);
}
