/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.load.validation;

import java.util.Date;

import org.eclipse.emf.common.util.EList;

import org.opencim.cim.iec61970.domain.SeasonName;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.load.Season}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SeasonValidator {
	boolean validate();

	boolean validateName(SeasonName value);
	boolean validateEndDate(Date value);
	boolean validateStartDate(Date value);
	boolean validateAreaLoadCurves(EList value);
	boolean validateLoadDemandModels(EList value);
}
