/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.load.validation;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.load.DayType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DayTypeValidator {
	boolean validate();

	boolean validateAreaLoadCurves(EList value);
	boolean validateLoadDemandModels(EList value);
}
