/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.load.validation;

import org.opencim.datatype.real.CurrentFlow;
import org.opencim.datatype.real.PerCent;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.load.EquivalentLoad}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EquivalentLoadValidator {
	boolean validate();

	boolean validateFeederLoadMgtFactor(PerCent value);
	boolean validateMVArColdPickUpFactor(PerCent value);
	boolean validateMWColdPickUpFactor(PerCent value);
	boolean validatePhaseAmpRating(CurrentFlow value);
	boolean validateLoadAllocationFactor(Float value);
}
