/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.load.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.datatype.real.PerCent;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.load.PowerCutZone}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PowerCutZoneValidator {
	boolean validate();

	boolean validateCutLevel1(PerCent value);
	boolean validateCutLevel2(PerCent value);
	boolean validateEnergyConsumers(EList value);
}
