/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.interpss.model.tests.Tree.validation;

import org.eclipse.emf.common.util.EList;

import org.interpss.model.tests.Tree.Node;

/**
 * A sample validator interface for {@link org.interpss.model.tests.Tree.Node}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NodeValidator {
	boolean validate();

	boolean validateLabel(String value);
	boolean validateChildList(EList<Node<Object>> value);
	boolean validateParent(Node<Object> value);
	boolean validateData(Object value);
}
