/**
 * <copyright>
 * 	Copyright www.interpss.com 2005
 * </copyright>
 * 
 * A JPanel for editing the model's data. It implements the IControllerEditor interface, which will be called from
 * the parent editor dialog.
 * 
 * @author  mzhou
 */

package org.interpss.dstab.control.script;

import java.util.Vector;

import com.interpss.common.ui.IControllerEditor;
import com.interpss.dstab.mach.Controller;

public class NBControllerScriptsEditPanel extends javax.swing.JPanel implements IControllerEditor {
	private static final long serialVersionUID = 1;

	private Controller controller = null;
	
    /** Creates new form FaultLocDataPanel */
    public NBControllerScriptsEditPanel() {
        initComponents();
    }
    
    /**
     * Init the editor panel, which will be called from its parent editor
     */
	public void init(Object cntler) {
		this.controller = (Controller)cntler;
	}
	
	/**
	*	Set controller data to the editor
	*
	* @return false if there is any problem
	*/
    public boolean setData2Editor() {
    	scriptsTextArea.setText(controller.getScripts());
        return true;
	}
    
	/**
	*	Save editor screen data to the controller data object
	*
	* @param errMsg error messages during the saving process.
	* @return false if there is any problem
	*/
    public boolean saveEditorData(Vector errMsg) throws Exception {
    	errMsg.clear();
    	controller.setScripts(scriptsTextArea.getText());
    	return true;
	}
    
	/** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        testAreaScrollPane = new javax.swing.JScrollPane();
        scriptsTextArea = new javax.swing.JTextArea();

        scriptsTextArea.setColumns(80);
        scriptsTextArea.setFont(new java.awt.Font("Courier New", 0, 12));
        scriptsTextArea.setRows(25);
        scriptsTextArea.setTabSize(3);
        testAreaScrollPane.setViewportView(scriptsTextArea);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(testAreaScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(testAreaScrollPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea scriptsTextArea;
    private javax.swing.JScrollPane testAreaScrollPane;
    // End of variables declaration//GEN-END:variables
}
