<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="editor"
    nsURI="http:///org/interpss/editor" nsPrefix="ipss">
  <eSubpackages name="ws" nsURI="http:///org/interpss/editor/ws" nsPrefix="ipss">
    <eClassifiers xsi:type="ecore:EClass" name="IpssWsDbItem" abstract="true" eSuperTypes="#//ws/IpssWsItem">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dbId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssWsItem" abstract="true">
      <eOperations name="isLoaded" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="clearDocument"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ipssDoc" eType="#//doc/IpssDocumentItem"
          eOpposite="#//doc/IpssDocumentItem/wsItem"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="NewItem"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//ws/IpssWsItemContainer"
          eOpposite="#//ws/IpssWsItemContainer/wsItemList"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssWsItemContainer" abstract="true"
        eSuperTypes="#//ws/IpssWsFileItem">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wsItemList" upperBound="-1"
          eType="#//ws/IpssWsItem" containment="true" eOpposite="#//ws/IpssWsItem/parent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssProjectItem" eSuperTypes="#//ws/IpssWsItem">
      <eOperations name="getParentProject" eType="#//ws/IpssProject"/>
      <eOperations name="getParentProjectItemGroup" eType="#//ws/IpssProjectItemGroup"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssWorkSpace" eSuperTypes="#//ws/IpssWsItemContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rootDir" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssProject" eSuperTypes="#//ws/IpssWsItemContainer">
      <eOperations name="getParanetFolder" eType="#//ws/IpssProjectFolder"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="projDbId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssProjectFolder" eSuperTypes="#//ws/IpssWsItemContainer">
      <eOperations name="getWorkSpace" eType="#//ws/IpssWorkSpace"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="WsItemInitStatus">
      <eLiterals name="Open"/>
      <eLiterals name="Active" value="1"/>
      <eLiterals name="Close" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssProjectItemGroup" eSuperTypes="#//ws/IpssWsItemContainer">
      <eOperations name="getParanetProject" eType="#//ws/IpssProject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="projDbId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssWsFileItem" abstract="true" eSuperTypes="#//ws/IpssWsItem">
      <eOperations name="getFilename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getFileExt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="getFilenameNoExt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eOperations name="isOpen" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eOperations name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="initStatus" eType="#//ws/WsItemInitStatus"
          defaultValueLiteral="Close"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="doc" nsURI="http:///org/interpss/editor/doc" nsPrefix="ipss">
    <eClassifiers xsi:type="ecore:EClass" name="IpssDocument" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="IpssDocumentItem" abstract="true"
        eSuperTypes="#//doc/IpssDocument">
      <eStructuralFeatures xsi:type="ecore:EReference" name="wsItem" lowerBound="1"
          eType="#//ws/IpssWsItem" eOpposite="#//ws/IpssWsItem/ipssDoc"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssEditorDocument" abstract="true"
        eSuperTypes="#//doc/IpssDocumentItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="IpssEditableDocument" abstract="true"
        eSuperTypes="#//doc/IpssEditorDocument">
      <eOperations name="getWsFileItem" eType="#//ws/IpssWsFileItem"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="modified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssSimuDocument" eSuperTypes="#//doc/IpssEditableDocument">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="appSimuCtx" eType="#//doc/AppSimuContext"
          transient="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IpssCustomDocument" eSuperTypes="#//doc/IpssSimuDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="IpssGraphicDocument" eSuperTypes="#//doc/IpssSimuDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="IpssReportDocument" eSuperTypes="#//doc/IpssEditorDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="IpssTextDocument" eSuperTypes="#//doc/IpssEditableDocument"/>
    <eClassifiers xsi:type="ecore:EClass" name="IpssXmlDocument" eSuperTypes="#//doc/IpssEditableDocument"/>
    <eClassifiers xsi:type="ecore:EDataType" name="AppSimuContext" instanceClassName="org.interpss.editor.jgraph.ui.app.IAppSimuContext"/>
    <eClassifiers xsi:type="ecore:EClass" name="IpssDbDocument" abstract="true" eSuperTypes="#//doc/IpssEditorDocument">
      <eOperations name="getWsDbItem" eType="#//ws/IpssWsDbItem"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
