 /*
  * @(#)NBAcscTransProjPanel.java   
  *
  * Copyright (C) 2006 www.interpss.org
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU LESSER GENERAL PUBLIC LICENSE
  * as published by the Free Software Foundation; either version 2.1
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * @Author Mike Zhou
  * @Version 1.0
  * @Date 09/15/2006
  * 
  *   Revision History
  *   ================
  *
  */

package org.interpss.editor.ui.edit.trans;
  
import java.util.Vector;

import org.interpss.editor.data.acsc.AcscNetData;
import org.interpss.editor.form.GFormContainer;
import org.interpss.editor.form.GNetForm;
import org.interpss.editor.jgraph.ui.edit.IFormDataPanel;
import org.interpss.editor.jgraph.ui.form.IGNetForm;

 
 
public class NBAcscTransProjPanel extends javax.swing.JPanel implements IFormDataPanel {
	private static final long serialVersionUID = 1;

	private GFormContainer _netContainer = null;

	public void initPanel() {
	}
    
	public void init(Object netContainer, Object form) {
		_netContainer = (GFormContainer)netContainer;
		setForm2Editor();
	}
	
    public boolean setForm2Editor() {
		GNetForm form = (GNetForm)_netContainer.getGNetForm();
		AcscNetData data = form.getAcscNetData();

		allowParalellBranchCheckBox.setSelected(form.isAllowParallelBranch());
		allowParalellBranchCheckBox.setEnabled(false);

		includeLFCheckBox.setSelected(data.isHasAclfData());
		if (includeLFCheckBox.isSelected()) {
			adjustmentCheckBox.setEnabled(true);
			adjustmentCheckBox.setSelected(data.isHasAdjustment());
		}
		else {
			adjustmentCheckBox.setEnabled(false);
		}
		
		return true;
	}
    
    public boolean saveEditor2Form(Vector errMsg) {
		GNetForm form = (GNetForm)_netContainer.getGNetForm();
		AcscNetData data = form.getAcscNetData();

		form.setNetType(IGNetForm.NetType_AcscNetwork);
		
		form.setAllowParallelBranch(allowParalellBranchCheckBox.isSelected());
		data.setHasAclfData(includeLFCheckBox.isSelected());
		if (includeLFCheckBox.isSelected()) 
			data.setHasAdjustment(adjustmentCheckBox.isSelected());
		return true;
    }
    
    /** Creates new form AclfEditPanel */
    public NBAcscTransProjPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allowParalellBranchCheckBox = new javax.swing.JCheckBox();
        includeLFCheckBox = new javax.swing.JCheckBox();
        adjustmentCheckBox = new javax.swing.JCheckBox();

        allowParalellBranchCheckBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        allowParalellBranchCheckBox.setSelected(true);
        allowParalellBranchCheckBox.setText("Allow paralell branches");
        allowParalellBranchCheckBox.setName("allowParalellBranchCheckBox"); // NOI18N

        includeLFCheckBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        includeLFCheckBox.setText("Include Loadflow Infomation");
        includeLFCheckBox.setName("includeLFCheckBox"); // NOI18N
        includeLFCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                includeLFCheckBoxActionPerformed(evt);
            }
        });

        adjustmentCheckBox.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        adjustmentCheckBox.setText("Include adjustments/controls");
        adjustmentCheckBox.setName("adjustmentCheckBox"); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(74, 74, 74)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(adjustmentCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 259, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(includeLFCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 209, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(allowParalellBranchCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 236, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(allowParalellBranchCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(includeLFCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(adjustmentCheckBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void includeLFCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_includeLFCheckBoxActionPerformed
		if (includeLFCheckBox.isSelected()) {
			adjustmentCheckBox.setEnabled(true);
		}
		else {
			adjustmentCheckBox.setEnabled(false);
		}
	}//GEN-LAST:event_includeLFCheckBoxActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adjustmentCheckBox;
    private javax.swing.JCheckBox allowParalellBranchCheckBox;
    private javax.swing.JCheckBox includeLFCheckBox;
    // End of variables declaration//GEN-END:variables
    
}
