<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="appSimu"
    nsURI="http://www.interpss.org/editor/appSimuCtx" nsPrefix="ipss.editor.appSimuCtx">
  <eClassifiers xsi:type="ecore:EClass" name="AppSimuContext">
    <eTypeParameters name="TSimuCtx"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastSimuRunType" eType="#//SimuRunType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aclfConverged" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scCalculated" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projData" eType="#//ProjectData"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="simuCtx">
      <eGenericType eTypeParameter="#//AppSimuContext/TSimuCtx"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectData"/>
  <eClassifiers xsi:type="ecore:EEnum" name="SimuRunType">
    <eLiterals name="ACLF" literal=""/>
    <eLiterals name="ACSC" value="1"/>
    <eLiterals name="DStab" value="2"/>
  </eClassifiers>
</ecore:EPackage>
