<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Document"
    nsURI="http://www.interpss.org/editor/document" nsPrefix="ipss.editor.doc">
  <eClassifiers xsi:type="ecore:EClass" name="IpssDocument">
    <eStructuralFeatures xsi:type="ecore:EReference" name="workspaceItem" eType="ecore:EClass workspace.ecore#//WorkspaceItem"
        eOpposite="workspace.ecore#//WorkspaceItem/ipssDocument"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssEditorDocument" eSuperTypes="#//IpssDocument">
    <eTypeParameters name="TViewer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="viewer">
      <eGenericType eTypeParameter="#//IpssEditorDocument/TViewer"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssEditableDocument">
    <eTypeParameters name="TEditor"/>
    <eTypeParameters name="TViewer"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modified" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eGenericSuperTypes eClassifier="#//IpssEditorDocument">
      <eTypeArguments eTypeParameter="#//IpssEditableDocument/TViewer"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssReportDocument">
    <eTypeParameters name="TViewer"/>
    <eGenericSuperTypes eClassifier="#//IpssEditorDocument">
      <eTypeArguments eTypeParameter="#//IpssReportDocument/TViewer"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssDBDocument">
    <eTypeParameters name="TViewer"/>
    <eGenericSuperTypes eClassifier="#//IpssEditorDocument">
      <eTypeArguments eTypeParameter="#//IpssDBDocument/TViewer"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssTextDocument">
    <eTypeParameters name="TEditor"/>
    <eTypeParameters name="TViewer"/>
    <eGenericSuperTypes eClassifier="#//IpssEditableDocument">
      <eTypeArguments eTypeParameter="#//IpssTextDocument/TEditor"/>
      <eTypeArguments eTypeParameter="#//IpssTextDocument/TViewer"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssSimuDocument">
    <eTypeParameters name="TSimuCtx"/>
    <eTypeParameters name="TEditor"/>
    <eTypeParameters name="TViewer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appSimuCtx" containment="true">
      <eGenericType eClassifier="ecore:EClass appSimuCtx.ecore#//AppSimuContext">
        <eTypeArguments eTypeParameter="#//IpssSimuDocument/TSimuCtx"/>
      </eGenericType>
    </eStructuralFeatures>
    <eGenericSuperTypes eClassifier="#//IpssEditableDocument">
      <eTypeArguments eTypeParameter="#//IpssSimuDocument/TEditor"/>
      <eTypeArguments eTypeParameter="#//IpssSimuDocument/TViewer"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssJGraphDocument">
    <eTypeParameters name="TAppSimuCtx"/>
    <eTypeParameters name="TEditor"/>
    <eTypeParameters name="TViewer"/>
    <eGenericSuperTypes eClassifier="#//IpssSimuDocument">
      <eTypeArguments eTypeParameter="#//IpssJGraphDocument/TAppSimuCtx"/>
      <eTypeArguments eTypeParameter="#//IpssJGraphDocument/TEditor"/>
      <eTypeArguments eTypeParameter="#//IpssJGraphDocument/TViewer"/>
    </eGenericSuperTypes>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssCustomDocument">
    <eTypeParameters name="TAppSimuCtx"/>
    <eTypeParameters name="TEditor"/>
    <eTypeParameters name="TViewer"/>
    <eGenericSuperTypes eClassifier="#//IpssSimuDocument">
      <eTypeArguments eTypeParameter="#//IpssCustomDocument/TAppSimuCtx"/>
      <eTypeArguments eTypeParameter="#//IpssCustomDocument/TEditor"/>
      <eTypeArguments eTypeParameter="#//IpssCustomDocument/TViewer"/>
    </eGenericSuperTypes>
  </eClassifiers>
</ecore:EPackage>
