/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.interpss.model.editor.doc.validation;

import org.interpss.model.editor.wkSpace.WorkspaceItem;

/**
 * A sample validator interface for {@link org.interpss.model.editor.doc.IpssDocument}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IpssDocumentValidator {
	boolean validate();

	boolean validateWorkspaceItem(WorkspaceItem value);
}
