/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.opencim.datatype.real.ActivePower;
import org.opencim.datatype.real.AngleRadians;
import org.opencim.datatype.real.Reactance;
import org.opencim.datatype.real.Resistance;
import org.opencim.datatype.real.Voltage;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.EquivalentSource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EquivalentSourceValidator {
	boolean validate();

	boolean validateXn(Reactance value);
	boolean validateRn(Resistance value);
	boolean validateNominalVoltage(Voltage value);
	boolean validateX(Reactance value);
	boolean validateR(Resistance value);
	boolean validateVoltageAngle(AngleRadians value);
	boolean validateVoltageMagnitude(Voltage value);
	boolean validateX0(Reactance value);
	boolean validateR0(Resistance value);
	boolean validateActivePower(ActivePower value);
}
