/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.topology.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.cim.iec61970.topology.TopologicalIsland;

import org.opencim.datatype.real.ActivePower;
import org.opencim.datatype.real.AngleRadians;
import org.opencim.datatype.real.ReactivePower;
import org.opencim.datatype.real.Voltage;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.topology.TopologicalNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TopologicalNodeValidator {
	boolean validate();

	boolean validateEnergized(Boolean value);
	boolean validateLoadCarrying(Boolean value);
	boolean validateNetInjectionMVar(ReactivePower value);
	boolean validateNetInjectionMW(ActivePower value);
	boolean validateObservabilityFlag(Boolean value);
	boolean validatePhaseAngle(AngleRadians value);
	boolean validateVoltage(Voltage value);
	boolean validateConnectivityNodes(EList value);
	boolean validateTopologicalIsland(TopologicalIsland value);
}
