/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.core.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.cim.iec61970.core.BasePower;

import org.opencim.datatype.real.Voltage;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.core.BaseVoltage}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BaseVoltageValidator {
	boolean validate();

	boolean validateNominalVoltage(Voltage value);
	boolean validateBasePower(BasePower value);
	boolean validateConductingEquipment(EList value);
	boolean validateVoltageLevel(EList value);
}
