package org.interpss.edispatch;

import org.interpss.BaseTestSetup;
import org.junit.Test;

public class ContingencyControlFileCaseTest extends BaseTestSetup {
	@Test
	public void simpleCaseTest() throws Exception {
/*
CONTINGENCY LOSEWESTBIGT
OPEN LINE FROM BUS 3004 TO BUS 152 CIRCUIT 1
END
CONTINGENCY LOSEEASTBIGT
OPEN LINE FROM BUS 151 TO BUS 201 CIRCUIT 1
END
CONTINGENCY LOSE2LINESWE
OPEN LINE FROM BUS 3004 TO BUS 152 CIRCUIT 1
OPEN LINE FROM BUS 3006 TO BUS 153 CIRCUIT 1
END
CONTINGENCY LOSE2LINEEA
OPEN LINE FROM BUS 151 TO BUS 201 CIRCUIT 1
OPEN LINE FROM BUS 152 TO BUS 202 CIRCUIT 1
END
END
*/
	}
}
