 /*
  * @(#)CalculationException.java   
  *
  * Copyright (C) 2006 www.interpss.com
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU LESSER GENERAL PUBLIC LICENSE
  * as published by the Free Software Foundation; either version 2.1
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * @Author Ron Oosterwijk
  * @Version 1.0
  * @Date Dec 2006
  * 
  *   Revision History
  *   ================
  *
  */

package abb.custom.dstab.pss.ieee.ieee2b;

import java.util.Vector;

import com.interpss.common.ui.IControllerEditor;
import com.interpss.common.ui.SwingInputVerifyUtil;
import com.interpss.common.util.Num2Str;

public class NBIEEE2BEditPanel extends javax.swing.JPanel implements IControllerEditor {
    /**
     *	Set form data to the editor
     *
     * @return false if there is any problem
     */
    public boolean setData2Editor() {
        ks1TextField.setText(Num2Str.toStr(_data.getKs1(), "#0.000"));
        ks2TextField.setText(Num2Str.toStr(_data.getKs2(), "#0.000"));
        ks3TextField.setText(Num2Str.toStr(_data.getKs3(), "#0.000"));
        tw1TextField.setText(Num2Str.toStr(_data.getTw1(), "#0.000"));
        tw2TextField.setText(Num2Str.toStr(_data.getTw2(), "#0.000"));
        tw3TextField.setText(Num2Str.toStr(_data.getTw3(), "#0.000"));
        t7TextField.setText(Num2Str.toStr(_data.getT7(), "#0.000"));
        t8TextField.setText(Num2Str.toStr(_data.getT8(), "#0.000"));
        t9TextField.setText(Num2Str.toStr(_data.getT9(), "#0.000"));
        mTextField.setText(Num2Str.toStr(_data.getM(), "#0.000"));
        nTextField.setText(Num2Str.toStr(_data.getN(), "#0.000"));
        t1TextField.setText(Num2Str.toStr(_data.getT1(), "#0.000"));
        t2TextField.setText(Num2Str.toStr(_data.getT2(), "#0.000"));
        t3TextField.setText(Num2Str.toStr(_data.getT3(), "#0.000"));
        t4TextField.setText(Num2Str.toStr(_data.getT4(), "#0.000"));
        t10TextField.setText(Num2Str.toStr(_data.getT10(), "#0.000"));
        t11TextField.setText(Num2Str.toStr(_data.getT11(), "#0.000"));
        vsmaxTextField.setText(Num2Str.toStr(_data.getVsmax(), "#0.000"));
        vsminTextField.setText(Num2Str.toStr(_data.getVsmin(), "#0.000"));
        
        return true;
    }
    
    /**
     *	Save editor screen data to the form
     *
     * @param errMsg error messages during the saving process.
     * @return false if there is any problem
     */
    public boolean saveEditorData(Vector errMsg) throws Exception {
        boolean ok = true;
        
        _data.setKs1(SwingInputVerifyUtil.getDouble(ks1TextField));
        _data.setKs2(SwingInputVerifyUtil.getDouble(ks2TextField));
        _data.setKs3(SwingInputVerifyUtil.getDouble(ks3TextField));
        _data.setT7(SwingInputVerifyUtil.getDouble(t7TextField));
        _data.setT8(SwingInputVerifyUtil.getDouble(t8TextField));
        _data.setT9(SwingInputVerifyUtil.getDouble(t9TextField));
        _data.setTw1(SwingInputVerifyUtil.getDouble(tw1TextField));
        _data.setTw2(SwingInputVerifyUtil.getDouble(tw2TextField));
        _data.setTw3(SwingInputVerifyUtil.getDouble(tw3TextField));
        _data.setM(SwingInputVerifyUtil.getDouble(mTextField));
        _data.setN(SwingInputVerifyUtil.getDouble(nTextField));
        _data.setT1(SwingInputVerifyUtil.getDouble(t1TextField));
        _data.setT2(SwingInputVerifyUtil.getDouble(t2TextField));
        _data.setT3(SwingInputVerifyUtil.getDouble(t3TextField));
        _data.setT4(SwingInputVerifyUtil.getDouble(t4TextField));
        _data.setT10(SwingInputVerifyUtil.getDouble(t10TextField));
        _data.setT11(SwingInputVerifyUtil.getDouble(t11TextField));
        _data.setVsmax(SwingInputVerifyUtil.getDouble(vsmaxTextField));
        _data.setVsmin(SwingInputVerifyUtil.getDouble(vsminTextField));
        
        return ok;
    }
    
    /*
     *  There is no need to make any change beyond this point
     */
    private static final long serialVersionUID = 1;
    IEEE2BData _data;
    
    /** Creates new form FaultLocDataPanel */
    public NBIEEE2BEditPanel() {
        initComponents();
    }
    
    public void init(Object controller) {
        _data = ((IEEE2B)controller).getData();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        ks1Label = new javax.swing.JLabel();
        ks1TextField = new javax.swing.JTextField();
        t1Label = new javax.swing.JLabel();
        t1TextField = new javax.swing.JTextField();
        t2Label = new javax.swing.JLabel();
        t2TextField = new javax.swing.JTextField();
        t3Label = new javax.swing.JLabel();
        t3TextField = new javax.swing.JTextField();
        t4Label = new javax.swing.JLabel();
        t4TextField = new javax.swing.JTextField();
        vsmaxLabel = new javax.swing.JLabel();
        vsmaxTextField = new javax.swing.JTextField();
        vsminLabel = new javax.swing.JLabel();
        vsminTextField = new javax.swing.JTextField();
        t4Label1 = new javax.swing.JLabel();
        t10TextField = new javax.swing.JTextField();
        t4Label2 = new javax.swing.JLabel();
        t11TextField = new javax.swing.JTextField();
        tw1Label = new javax.swing.JLabel();
        tw1TextField = new javax.swing.JTextField();
        tw2Label = new javax.swing.JLabel();
        tw2TextField = new javax.swing.JTextField();
        tw3Label = new javax.swing.JLabel();
        tw3TextField = new javax.swing.JTextField();
        ks2Label = new javax.swing.JLabel();
        ks2TextField = new javax.swing.JTextField();
        T7Label = new javax.swing.JLabel();
        t7TextField = new javax.swing.JTextField();
        t8Label = new javax.swing.JLabel();
        t8TextField = new javax.swing.JTextField();
        t9Label = new javax.swing.JLabel();
        t9TextField = new javax.swing.JTextField();
        mLabel = new javax.swing.JLabel();
        mTextField = new javax.swing.JTextField();
        nLabel = new javax.swing.JLabel();
        nTextField = new javax.swing.JTextField();
        ks3Label = new javax.swing.JLabel();
        ks3TextField = new javax.swing.JTextField();

        ks1Label.setFont(new java.awt.Font("Dialog", 0, 12));
        ks1Label.setText("KS1 (pu)");

        ks1TextField.setColumns(5);
        ks1TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        ks1TextField.setText("1.0");

        t1Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t1Label.setText("T1(s)");

        t1TextField.setColumns(5);
        t1TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t1TextField.setText("0.050");

        t2Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t2Label.setText("T2(s)");

        t2TextField.setColumns(5);
        t2TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t2TextField.setText("0.500");

        t3Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t3Label.setText("T3(s)");

        t3TextField.setColumns(5);
        t3TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t3TextField.setText("0.050");

        t4Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t4Label.setText("T4(s)");

        t4TextField.setColumns(5);
        t4TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t4TextField.setText("0.250");

        vsmaxLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        vsmaxLabel.setText("Vsmax(pu)");

        vsmaxTextField.setColumns(5);
        vsmaxTextField.setFont(new java.awt.Font("Dialog", 0, 12));
        vsmaxTextField.setText("0.200");

        vsminLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        vsminLabel.setText("Vsmin(pu)");

        vsminTextField.setColumns(5);
        vsminTextField.setFont(new java.awt.Font("Dialog", 0, 12));
        vsminTextField.setText("-0.200");

        t4Label1.setFont(new java.awt.Font("Dialog", 0, 12));
        t4Label1.setText("T10 (s)");

        t10TextField.setColumns(5);
        t10TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t10TextField.setText("0.250");

        t4Label2.setFont(new java.awt.Font("Dialog", 0, 12));
        t4Label2.setText("T11 (s)");

        t11TextField.setColumns(5);
        t11TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t11TextField.setText("0.250");

        tw1Label.setFont(new java.awt.Font("Dialog", 0, 12));
        tw1Label.setText("TW1 (s)");

        tw1TextField.setColumns(5);
        tw1TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        tw1TextField.setText("5.00");

        tw2Label.setFont(new java.awt.Font("Dialog", 0, 12));
        tw2Label.setText("TW2 (s)");

        tw2TextField.setColumns(5);
        tw2TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        tw2TextField.setText("5.00");

        tw3Label.setFont(new java.awt.Font("Dialog", 0, 12));
        tw3Label.setText("TW3 (s)");

        tw3TextField.setColumns(5);
        tw3TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        tw3TextField.setText("5.00");

        ks2Label.setFont(new java.awt.Font("Dialog", 0, 12));
        ks2Label.setText("KS2 (pu)");

        ks2TextField.setColumns(5);
        ks2TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        ks2TextField.setText("0.7500");

        T7Label.setFont(new java.awt.Font("Dialog", 0, 12));
        T7Label.setText("T7 (s)");

        t7TextField.setColumns(5);
        t7TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t7TextField.setText("5.00");

        t8Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t8Label.setText("T8 (s)");

        t8TextField.setColumns(5);
        t8TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t8TextField.setText("0.000");

        t9Label.setFont(new java.awt.Font("Dialog", 0, 12));
        t9Label.setText("T9 (s)");

        t9TextField.setColumns(5);
        t9TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        t9TextField.setText("0.100");

        mLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        mLabel.setText("M");

        mTextField.setColumns(5);
        mTextField.setFont(new java.awt.Font("Dialog", 0, 12));
        mTextField.setText("1");

        nLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        nLabel.setText("N");

        nTextField.setColumns(5);
        nTextField.setFont(new java.awt.Font("Dialog", 0, 12));
        nTextField.setText("5");

        ks3Label.setFont(new java.awt.Font("Dialog", 0, 12));
        ks3Label.setText("KS3 (pu)");

        ks3TextField.setColumns(5);
        ks3TextField.setFont(new java.awt.Font("Dialog", 0, 12));
        ks3TextField.setText("1.000");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(ks3Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(ks3TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(T7Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                        .add(t7TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tw2Label)
                            .add(tw1Label))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 9, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(tw1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tw2TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(tw3Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 9, Short.MAX_VALUE)
                        .add(tw3TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(ks2Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(ks2TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(25, 25, 25)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(vsminLabel)
                    .add(ks1Label)
                    .add(t8Label)
                    .add(t9Label)
                    .add(mLabel)
                    .add(nLabel))
                .add(17, 17, 17)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(nTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(vsminTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(mTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(t9TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(t8TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ks1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(49, 49, 49)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .add(vsmaxLabel)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 29, Short.MAX_VALUE)
                        .add(vsmaxTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(t4Label2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                        .add(t11TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(t4Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                        .add(t4TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(t3Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                        .add(t3TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(t2Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                        .add(t2TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(t1Label)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                        .add(t1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createSequentialGroup()
                        .add(t4Label1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 49, Short.MAX_VALUE)
                        .add(t10TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ks1Label)
                            .add(tw1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tw1Label)
                            .add(ks1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(t1Label)))
                    .add(t1TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(t2TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(t2Label))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(t3Label)
                            .add(t3TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(t4TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(t4Label)
                            .add(mLabel)
                            .add(ks2TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ks2Label)))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(tw2TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(t8Label))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(tw2Label))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(t8TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(tw3Label)
                                .add(tw3TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(t9Label))
                            .add(t9TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(mTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(6, 6, 6)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(t7TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(T7Label)
                            .add(nLabel))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(ks3TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(ks3Label))
                        .add(53, 53, 53))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(t10TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(t4Label1))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                    .add(t4Label2)
                                    .add(t11TextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(layout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(nTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(vsmaxTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(vsmaxLabel)
                            .add(vsminTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(vsminLabel))
                        .add(25, 25, 25))))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel T7Label;
    private javax.swing.JLabel ks1Label;
    private javax.swing.JTextField ks1TextField;
    private javax.swing.JLabel ks2Label;
    private javax.swing.JTextField ks2TextField;
    private javax.swing.JLabel ks3Label;
    private javax.swing.JTextField ks3TextField;
    private javax.swing.JLabel mLabel;
    private javax.swing.JTextField mTextField;
    private javax.swing.JLabel nLabel;
    private javax.swing.JTextField nTextField;
    private javax.swing.JTextField t10TextField;
    private javax.swing.JTextField t11TextField;
    private javax.swing.JLabel t1Label;
    private javax.swing.JTextField t1TextField;
    private javax.swing.JLabel t2Label;
    private javax.swing.JTextField t2TextField;
    private javax.swing.JLabel t3Label;
    private javax.swing.JTextField t3TextField;
    private javax.swing.JLabel t4Label;
    private javax.swing.JLabel t4Label1;
    private javax.swing.JLabel t4Label2;
    private javax.swing.JTextField t4TextField;
    private javax.swing.JTextField t7TextField;
    private javax.swing.JLabel t8Label;
    private javax.swing.JTextField t8TextField;
    private javax.swing.JLabel t9Label;
    private javax.swing.JTextField t9TextField;
    private javax.swing.JLabel tw1Label;
    private javax.swing.JTextField tw1TextField;
    private javax.swing.JLabel tw2Label;
    private javax.swing.JTextField tw2TextField;
    private javax.swing.JLabel tw3Label;
    private javax.swing.JTextField tw3TextField;
    private javax.swing.JLabel vsmaxLabel;
    private javax.swing.JTextField vsmaxTextField;
    private javax.swing.JLabel vsminLabel;
    private javax.swing.JTextField vsminTextField;
    // End of variables declaration//GEN-END:variables
}
