 /*
  * @(#)NBSearchBusPanel.java   
  *
  * Copyright (C) 2006 www.interpss.org
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU LESSER GENERAL PUBLIC LICENSE
  * as published by the Free Software Foundation; either version 2.1
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * @Author Mike Zhou
  * @Version 1.0
  * @Date 09/15/2006
  * 
  *   Revision History
  *   ================
  *
  */

package org.interpss.editor.ui.edit.common;

import org.interpss.editor.data.dist.DistBusData;
import org.interpss.editor.form.GBusForm;
import org.interpss.editor.form.GFormContainer;
import org.interpss.editor.jgraph.ui.form.IGNetForm;


public class NBSearchBusPanel extends javax.swing.JPanel {
	private static final long serialVersionUID = 1;

	private GFormContainer _netContainer = null;

    public void init(GFormContainer netContainer) {
        _netContainer = netContainer;
        
        busNoComboBox.setModel(new javax.swing.DefaultComboBoxModel(_netContainer.getBusIdArray()));
        busNameComboBox.setModel(new javax.swing.DefaultComboBoxModel(_netContainer.getBusNameArray()));

        busTypePanel.removeAll();
        if (netContainer.getGNetForm().getAppType().equals(IGNetForm.AppType_Distribution)) {
            busTypePanel.setLayout(new java.awt.GridLayout(1, 0));
        	busTypePanel.add(distBusTypePanel);
			allDistRadioButton.setSelected(true);

            // TODO: this.areaComboBox
            //	     this.zoneComboBox

        }
        else if (netContainer.getGNetForm().getAppType().equals(IGNetForm.AppType_Transmission)) {
            if (netContainer.getGNetForm().getNetType().equals(IGNetForm.NetType_AcscNetwork)) {
            	busTypePanel.setLayout(new java.awt.GridLayout(2, 0));
            	java.awt.GridBagConstraints gridBagConstraints = new java.awt.GridBagConstraints();
            	gridBagConstraints.gridy = 0;
            	busTypePanel.add(aclfBusTypePanel, gridBagConstraints);
            	gridBagConstraints.gridy = 1;
            	busTypePanel.add(acscBusTypePanel, gridBagConstraints);
            }
            else {
            	busTypePanel.setLayout(new java.awt.GridLayout(1, 0));
            	busTypePanel.add(aclfBusTypePanel);
            }
        }

        this.busNoComboBox.setSelectedIndex(0);
        this.busNameComboBox.setSelectedIndex(0);
    }
    
    public GBusForm getSelectedObj() {
        String id = (String)this.busNoComboBox.getSelectedItem();
        return (GBusForm)_netContainer.getGBusForm(id);
    }
    
    /** Creates new form NBFindBusPanel */
    public NBSearchBusPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        distBusTypeButtonGroup = new javax.swing.ButtonGroup();
        aclfBusTypeButtonGroup = new javax.swing.ButtonGroup();
        acscBusTypeButtonGroup = new javax.swing.ButtonGroup();
        busTypePanel = new javax.swing.JPanel();
        distBusTypePanel = new javax.swing.JPanel();
        allDistRadioButton = new javax.swing.JRadioButton();
        utilityRadioButton = new javax.swing.JRadioButton();
        generatorRadioButton = new javax.swing.JRadioButton();
        synMotorRadioButton = new javax.swing.JRadioButton();
        indMotorRadioButton = new javax.swing.JRadioButton();
        nonContriRadioButton = new javax.swing.JRadioButton();
        aclfBusTypePanel = new javax.swing.JPanel();
        allAclfRadioButton = new javax.swing.JRadioButton();
        swingRadioButton = new javax.swing.JRadioButton();
        pvRadioButton = new javax.swing.JRadioButton();
        pqRadioButton = new javax.swing.JRadioButton();
        capacitorRadioButton = new javax.swing.JRadioButton();
        loadRadioButton = new javax.swing.JRadioButton();
        nonGenLoadRadioButton = new javax.swing.JRadioButton();
        acscBusTypePanel = new javax.swing.JPanel();
        acscAllRadioButton = new javax.swing.JRadioButton();
        contributeRadioButton = new javax.swing.JRadioButton();
        nonContributeRadioButton = new javax.swing.JRadioButton();
        areaZonePanel = new javax.swing.JPanel();
        areaLabel = new javax.swing.JLabel();
        areaComboBox = new javax.swing.JComboBox();
        zoneLabel = new javax.swing.JLabel();
        zoneComboBox = new javax.swing.JComboBox();
        selectPanel = new javax.swing.JPanel();
        busNameLabel = new javax.swing.JLabel();
        busNameComboBox = new javax.swing.JComboBox();
        busNoLabel = new javax.swing.JLabel();
        busNoComboBox = new javax.swing.JComboBox();

        setLayout(new java.awt.BorderLayout());

        setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 10, 0, 10)));
        busTypePanel.setLayout(new java.awt.GridBagLayout());

        busTypePanel.setBorder(new javax.swing.border.TitledBorder(null, "Distribution Bus Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 10)));
        distBusTypeButtonGroup.add(allDistRadioButton);
        allDistRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        allDistRadioButton.setSelected(true);
        allDistRadioButton.setText("All");
        allDistRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allDistRadioButtonActionPerformed(evt);
            }
        });

        distBusTypePanel.add(allDistRadioButton);

        distBusTypeButtonGroup.add(utilityRadioButton);
        utilityRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        utilityRadioButton.setText("Utility");
        utilityRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilityRadioButtonActionPerformed(evt);
            }
        });

        distBusTypePanel.add(utilityRadioButton);

        distBusTypeButtonGroup.add(generatorRadioButton);
        generatorRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        generatorRadioButton.setText("Generator");
        generatorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatorRadioButtonActionPerformed(evt);
            }
        });

        distBusTypePanel.add(generatorRadioButton);

        distBusTypeButtonGroup.add(synMotorRadioButton);
        synMotorRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        synMotorRadioButton.setText("SynMotor");
        synMotorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                synMotorRadioButtonActionPerformed(evt);
            }
        });

        distBusTypePanel.add(synMotorRadioButton);

        distBusTypeButtonGroup.add(indMotorRadioButton);
        indMotorRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        indMotorRadioButton.setText("IndMotor");
        indMotorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indMotorRadioButtonActionPerformed(evt);
            }
        });

        distBusTypePanel.add(indMotorRadioButton);

        distBusTypeButtonGroup.add(nonContriRadioButton);
        nonContriRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        nonContriRadioButton.setText("NonContribute");
        nonContriRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonContriRadioButtonActionPerformed(evt);
            }
        });

        distBusTypePanel.add(nonContriRadioButton);

        busTypePanel.add(distBusTypePanel, new java.awt.GridBagConstraints());

        aclfBusTypeButtonGroup.add(allAclfRadioButton);
        allAclfRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        allAclfRadioButton.setSelected(true);
        allAclfRadioButton.setText("All");
        allAclfRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allAclfRadioButtonActionPerformed(evt);
            }
        });

        aclfBusTypePanel.add(allAclfRadioButton);

        aclfBusTypeButtonGroup.add(swingRadioButton);
        swingRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        swingRadioButton.setText("Swing");
        swingRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swingRadioButtonActionPerformed(evt);
            }
        });

        aclfBusTypePanel.add(swingRadioButton);

        aclfBusTypeButtonGroup.add(pvRadioButton);
        pvRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        pvRadioButton.setText("PV");
        pvRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pvRadioButtonActionPerformed(evt);
            }
        });

        aclfBusTypePanel.add(pvRadioButton);

        pqRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        pqRadioButton.setText("PQ");
        pqRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pqRadioButtonActionPerformed(evt);
            }
        });

        aclfBusTypePanel.add(pqRadioButton);

        aclfBusTypeButtonGroup.add(capacitorRadioButton);
        capacitorRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        capacitorRadioButton.setText("Capacitor");
        capacitorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capacitorRadioButtonActionPerformed(evt);
            }
        });

        aclfBusTypePanel.add(capacitorRadioButton);

        loadRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        loadRadioButton.setText("Load");
        loadRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadRadioButtonActionPerformed(evt);
            }
        });

        aclfBusTypePanel.add(loadRadioButton);

        nonGenLoadRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        nonGenLoadRadioButton.setText("NonGenLoad");
        nonGenLoadRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonGenLoadRadioButtonActionPerformed(evt);
            }
        });

        aclfBusTypePanel.add(nonGenLoadRadioButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 1;
        busTypePanel.add(aclfBusTypePanel, gridBagConstraints);

        acscBusTypeButtonGroup.add(acscAllRadioButton);
        acscAllRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        acscAllRadioButton.setSelected(true);
        acscAllRadioButton.setText("All");
        acscAllRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acscAllRadioButtonActionPerformed(evt);
            }
        });

        acscBusTypePanel.add(acscAllRadioButton);

        acscBusTypeButtonGroup.add(contributeRadioButton);
        contributeRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        contributeRadioButton.setText("Contribute");
        contributeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contributeRadioButtonActionPerformed(evt);
            }
        });

        acscBusTypePanel.add(contributeRadioButton);

        nonContributeRadioButton.setFont(new java.awt.Font("Dialog", 0, 12));
        nonContributeRadioButton.setText("NonContribute");
        nonContributeRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonContributeRadioButtonActionPerformed(evt);
            }
        });

        acscBusTypePanel.add(nonContributeRadioButton);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 2;
        busTypePanel.add(acscBusTypePanel, gridBagConstraints);

        add(busTypePanel, java.awt.BorderLayout.NORTH);

        areaZonePanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 1, 1, 1)));
        areaLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        areaLabel.setText("Area");
        areaZonePanel.add(areaLabel);

        areaComboBox.setFont(new java.awt.Font("Dialog", 0, 12));
        areaComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));
        areaComboBox.setPreferredSize(new java.awt.Dimension(50, 22));
        areaComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                areaComboBoxActionPerformed(evt);
            }
        });

        areaZonePanel.add(areaComboBox);

        zoneLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        zoneLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        zoneLabel.setText("Zone");
        zoneLabel.setPreferredSize(new java.awt.Dimension(75, 15));
        areaZonePanel.add(zoneLabel);

        zoneComboBox.setFont(new java.awt.Font("Dialog", 0, 12));
        zoneComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All" }));
        zoneComboBox.setPreferredSize(new java.awt.Dimension(50, 21));
        zoneComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoneComboBoxActionPerformed(evt);
            }
        });

        areaZonePanel.add(zoneComboBox);

        add(areaZonePanel, java.awt.BorderLayout.CENTER);

        selectPanel.setBorder(new javax.swing.border.EmptyBorder(new java.awt.Insets(10, 1, 10, 1)));
        busNameLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        busNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        busNameLabel.setText("Bus Name");
        busNameLabel.setPreferredSize(new java.awt.Dimension(60, 16));
        selectPanel.add(busNameLabel);

        busNameComboBox.setFont(new java.awt.Font("Dialog", 0, 12));
        busNameComboBox.setPreferredSize(new java.awt.Dimension(100, 21));
        busNameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busNameComboBoxActionPerformed(evt);
            }
        });

        selectPanel.add(busNameComboBox);

        busNoLabel.setFont(new java.awt.Font("Dialog", 0, 12));
        busNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        busNoLabel.setText("Bus Number");
        busNoLabel.setPreferredSize(new java.awt.Dimension(100, 16));
        selectPanel.add(busNoLabel);

        busNoComboBox.setFont(new java.awt.Font("Dialog", 0, 12));
        busNoComboBox.setPreferredSize(new java.awt.Dimension(100, 21));
        busNoComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busNoComboBoxActionPerformed(evt);
            }
        });

        selectPanel.add(busNoComboBox);

        add(selectPanel, java.awt.BorderLayout.SOUTH);

    }
    // </editor-fold>//GEN-END:initComponents

    private void nonContributeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonContributeRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_nonContributeRadioButtonActionPerformed

    private void contributeRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contributeRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_contributeRadioButtonActionPerformed

    private void acscAllRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acscAllRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_acscAllRadioButtonActionPerformed

    private void nonGenLoadRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonGenLoadRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_nonGenLoadRadioButtonActionPerformed

    private void loadRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_loadRadioButtonActionPerformed

    private void capacitorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capacitorRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_capacitorRadioButtonActionPerformed

    private void pqRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pqRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_pqRadioButtonActionPerformed

    private void pvRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pvRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_pvRadioButtonActionPerformed

    private void swingRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swingRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_swingRadioButtonActionPerformed

    private void allAclfRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allAclfRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_allAclfRadioButtonActionPerformed

    private void busNameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busNameComboBoxActionPerformed
		if (this.busNameComboBox.getSelectedIndex()>=0)
			this.busNoComboBox.setSelectedIndex(this.busNameComboBox.getSelectedIndex());
    }//GEN-LAST:event_busNameComboBoxActionPerformed

    private void busNoComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busNoComboBoxActionPerformed
    }//GEN-LAST:event_busNoComboBoxActionPerformed

    private void zoneComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoneComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zoneComboBoxActionPerformed

    private void areaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_areaComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_areaComboBoxActionPerformed

    private void nonContriRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonContriRadioButtonActionPerformed
        this.busNoComboBox.setModel(
                new javax.swing.DefaultComboBoxModel(_netContainer.getDistBusIdArray(DistBusData.BusCode_NonContribute)));
        this.busNoComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_nonContriRadioButtonActionPerformed

    private void indMotorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indMotorRadioButtonActionPerformed
        this.busNoComboBox.setModel(
                new javax.swing.DefaultComboBoxModel(_netContainer.getDistBusIdArray(DistBusData.BusCode_IndMotor)));
        this.busNoComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_indMotorRadioButtonActionPerformed

    private void synMotorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_synMotorRadioButtonActionPerformed
        this.busNoComboBox.setModel(
                new javax.swing.DefaultComboBoxModel(_netContainer.getDistBusIdArray(DistBusData.BusCode_SynMotor)));
        this.busNoComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_synMotorRadioButtonActionPerformed

    private void generatorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatorRadioButtonActionPerformed
        this.busNoComboBox.setModel(
                new javax.swing.DefaultComboBoxModel(_netContainer.getDistBusIdArray(DistBusData.BusCode_Generator)));
        this.busNoComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_generatorRadioButtonActionPerformed

    private void utilityRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilityRadioButtonActionPerformed
        this.busNoComboBox.setModel(
                new javax.swing.DefaultComboBoxModel(_netContainer.getDistBusIdArray(DistBusData.BusCode_Utility)));
        this.busNoComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_utilityRadioButtonActionPerformed

    private void allDistRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allDistRadioButtonActionPerformed
        this.busNoComboBox.setModel(
                new javax.swing.DefaultComboBoxModel(_netContainer.getDistBusIdArray(DistBusData.BusCode_AllBus)));
        this.busNoComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_allDistRadioButtonActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup aclfBusTypeButtonGroup;
    private javax.swing.JPanel aclfBusTypePanel;
    private javax.swing.JRadioButton acscAllRadioButton;
    private javax.swing.ButtonGroup acscBusTypeButtonGroup;
    private javax.swing.JPanel acscBusTypePanel;
    private javax.swing.JRadioButton allAclfRadioButton;
    private javax.swing.JRadioButton allDistRadioButton;
    private javax.swing.JComboBox areaComboBox;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JPanel areaZonePanel;
    private javax.swing.JComboBox busNameComboBox;
    private javax.swing.JLabel busNameLabel;
    private javax.swing.JComboBox busNoComboBox;
    private javax.swing.JLabel busNoLabel;
    private javax.swing.JPanel busTypePanel;
    private javax.swing.JRadioButton capacitorRadioButton;
    private javax.swing.JRadioButton contributeRadioButton;
    private javax.swing.ButtonGroup distBusTypeButtonGroup;
    private javax.swing.JPanel distBusTypePanel;
    private javax.swing.JRadioButton generatorRadioButton;
    private javax.swing.JRadioButton indMotorRadioButton;
    private javax.swing.JRadioButton loadRadioButton;
    private javax.swing.JRadioButton nonContriRadioButton;
    private javax.swing.JRadioButton nonContributeRadioButton;
    private javax.swing.JRadioButton nonGenLoadRadioButton;
    private javax.swing.JRadioButton pqRadioButton;
    private javax.swing.JRadioButton pvRadioButton;
    private javax.swing.JPanel selectPanel;
    private javax.swing.JRadioButton swingRadioButton;
    private javax.swing.JRadioButton synMotorRadioButton;
    private javax.swing.JRadioButton utilityRadioButton;
    private javax.swing.JComboBox zoneComboBox;
    private javax.swing.JLabel zoneLabel;
    // End of variables declaration//GEN-END:variables
    
}
