/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.opencim.cim.iec61970.wire.ConductorType;

import org.opencim.datatype.real.Conductance;
import org.opencim.datatype.real.LongLength;
import org.opencim.datatype.real.Reactance;
import org.opencim.datatype.real.Resistance;
import org.opencim.datatype.real.Susceptance;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.Conductor}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConductorValidator {
	boolean validate();

	boolean validateB0ch(Susceptance value);
	boolean validateBch(Susceptance value);
	boolean validateG0ch(Conductance value);
	boolean validateGch(Conductance value);
	boolean validateLength(LongLength value);
	boolean validateR(Resistance value);
	boolean validateR0(Resistance value);
	boolean validateX(Reactance value);
	boolean validateX0(Reactance value);
	boolean validateConductorType(ConductorType value);
}
