/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.opencim.cim.iec61970.wire.Line;

import org.opencim.datatype.real.Inductance;
import org.opencim.datatype.real.Resistance;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.DCLineSegment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DCLineSegmentValidator {
	boolean validate();

	boolean validateDcSegmentInductance(Inductance value);
	boolean validateDcSegmentResistance(Resistance value);
	boolean validateLine(Line value);
}
