/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.datatype.real.Pressure;
import org.opencim.datatype.real.Temperature;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.MVArCapabilityCurve}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MVArCapabilityCurveValidator {
	boolean validate();

	boolean validateCoolantTemperature(Temperature value);
	boolean validateHydrogenPressure(Pressure value);
	boolean validateSynchronousMachines(EList value);
}
