/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import java.util.Date;

import org.opencim.cim.iec61970.wire.CompositeSwitch;

import org.opencim.datatype.integer.Counter;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.Switch}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SwitchValidator {
	boolean validate();

	boolean validateNormalOpen(Boolean value);
	boolean validateSwitchOnCount(Counter value);
	boolean validateSwitchOnDate(Date value);
	boolean validateCompositeSwitch(CompositeSwitch value);
}
