/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.cim.iec61970.domain.WindingConnection;
import org.opencim.cim.iec61970.domain.WindingType;

import org.opencim.cim.iec61970.wire.PowerTransformer;
import org.opencim.cim.iec61970.wire.WindingTest;

import org.opencim.datatype.real.ApparentPower;
import org.opencim.datatype.real.Conductance;
import org.opencim.datatype.real.Reactance;
import org.opencim.datatype.real.Resistance;
import org.opencim.datatype.real.Susceptance;
import org.opencim.datatype.real.Voltage;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.TransformerWinding}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransformerWindingValidator {
	boolean validate();

	boolean validateB(Susceptance value);
	boolean validateInsulationKV(Voltage value);
	boolean validateConnectionType(WindingConnection value);
	boolean validateEmergencyMVA(ApparentPower value);
	boolean validateG(Conductance value);
	boolean validateGrounded(Boolean value);
	boolean validateR(Resistance value);
	boolean validateR0(Resistance value);
	boolean validateRatedKV(Voltage value);
	boolean validateRatedMVA(ApparentPower value);
	boolean validateRground(Resistance value);
	boolean validateShortTermMVA(ApparentPower value);
	boolean validateWindingType(WindingType value);
	boolean validateX(Reactance value);
	boolean validateX0(Reactance value);
	boolean validateXground(Reactance value);
	boolean validatePowerTransformer(PowerTransformer value);
	boolean validateTapChangers(EList value);
	boolean validateFrom_WindingTests(EList value);
	boolean validateTo_WindingTest(WindingTest value);
}
