/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.wire.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.datatype.integer.Counter;

import org.opencim.datatype.real.CurrentFlow;
import org.opencim.datatype.real.Resistance;
import org.opencim.datatype.real.ShortLength;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.wire.WireType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WireTypeValidator {
	boolean validate();

	boolean validatePhaseConductorCount(Counter value);
	boolean validatePhaseConductorSpacing(ShortLength value);
	boolean validateAmpRating(CurrentFlow value);
	boolean validateGMR(ShortLength value);
	boolean validateRadius(ShortLength value);
	boolean validateResistance(Resistance value);
	boolean validateWireArrangements(EList value);
}
