<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="wkSpace"
    nsURI="http://www.interpss.org/editor/workspace" nsPrefix="ipss.editor.workspace">
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//WorkspaceItemContainer"
        eOpposite="#//WorkspaceItemContainer/wsItemList"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ipssDocument" eType="ecore:EClass document.ecore#//IpssDocument"
        containment="true" eOpposite="document.ecore#//IpssDocument/workspaceItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceItemContainer" eSuperTypes="#//WorkspaceItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="wsItemList" upperBound="-1"
        eType="#//WorkspaceItem" containment="true" resolveProxies="false" eOpposite="#//WorkspaceItem/parent"
        eKeys="#//WorkspaceItem/name"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssProjectItem" eSuperTypes="#//WorkspaceItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initStatus" eType="#//ProjectItemStatus"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssWorkspace" eSuperTypes="#//WorkspaceItemContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absolutionPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssProjectFolder" eSuperTypes="#//WorkspaceItemContainer"/>
  <eClassifiers xsi:type="ecore:EClass" name="IpssProject" eSuperTypes="#//WorkspaceItemContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projDbId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IpssProjectItemGroup" eSuperTypes="#//WorkspaceItemContainer"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ProjectItemStatus">
    <eLiterals name="Open"/>
    <eLiterals name="Close" value="1"/>
    <eLiterals name="Active" value="2"/>
  </eClassifiers>
</ecore:EPackage>
