/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.core.validation;

import org.opencim.cim.iec61970.core.Substation;
import org.opencim.cim.iec61970.core.VoltageLevel;

import org.opencim.cim.iec61970.domain.BreakerConfiguration;
import org.opencim.cim.iec61970.domain.BusbarConfiguration;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.core.Bay}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BayValidator {
	boolean validate();

	boolean validateBayEnergyMeasFlag(Boolean value);
	boolean validateBayPowerMeasFlag(Boolean value);
	boolean validateBreakerConfiguration(BreakerConfiguration value);
	boolean validateBusBarConfiguration(BusbarConfiguration value);
	boolean validateVoltageLevel(VoltageLevel value);
	boolean validateSubstation(Substation value);
}
