/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.opencim.cim.iec61970.core.validation;

import org.eclipse.emf.common.util.EList;

import org.opencim.cim.iec61970.core.BaseVoltage;

import org.opencim.datatype.string.PhaseCode;

/**
 * A sample validator interface for {@link org.opencim.cim.iec61970.core.ConductingEquipment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConductingEquipmentValidator {
	boolean validate();

	boolean validatePhases(PhaseCode value);
	boolean validateTerminals(EList value);
	boolean validateBaseVoltage(BaseVoltage value);
}
