/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package org.interpss.editor.ws.validation;

import org.interpss.editor.doc.IpssDocument;
import org.interpss.editor.ws.IpssWsItemContainer;


/**
 * A sample validator interface for {@link org.interpss.editor.ws.IpssWsItem}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IpssWsItemValidator {
	boolean validate();

	boolean validateIpssDoc(IpssDocument value);

	boolean validateName(String value);

	boolean validateParent(IpssWsItemContainer value);

}
