package com.interpss.editor.ui.edit.trans;
  
/**
 *
 */
import java.util.Vector;

import com.interpss.editor.data.dstab.DStabNetData;
import com.interpss.editor.form.GFormContainer;
import com.interpss.editor.form.GNetForm;
import com.interpss.editor.jgraph.ui.edit.IFormDataPanel;
import com.interpss.editor.jgraph.ui.form.IGNetForm;
 
 
public class NBDStabTransProjPanel extends javax.swing.JPanel implements IFormDataPanel {
	private static final long serialVersionUID = 1;

	private GFormContainer _netContainer = null;

	public void initPanel() {
	}
    
	public void init(Object netContainer, Object form) {
		_netContainer = (GFormContainer)netContainer;
	}
	
    public boolean setForm2Editor() {
		GNetForm form = (GNetForm)_netContainer.getGNetForm();
		allowParalellBranchCheckBox.setSelected(form.isAllowParallelBranch());
		allowParalellBranchCheckBox.setEnabled(false);
		
		adjustmentCheckBox.setSelected(form.getAcscNetData().isHasAdjustment());
    	return true;
	}
    
    public boolean saveEditor2Form(Vector errMsg) {
		GNetForm form = (GNetForm)_netContainer.getGNetForm();
		DStabNetData data = form.getDStabNetData();

		form.setNetType(IGNetForm.NetType_DStabilityNet);

		form.setAllowParallelBranch(allowParalellBranchCheckBox.isSelected());
		
		if (adjustmentCheckBox.isSelected()) {
			data.getAcscNetData().setHasAdjustment(true);
		}
		return true;
    }
    
    /** Creates new form AclfEditPanel */
    public NBDStabTransProjPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        allowParalellBranchCheckBox = new javax.swing.JCheckBox();
        adjustmentCheckBox = new javax.swing.JCheckBox();

        setLayout(new java.awt.GridLayout(2, 1));

        allowParalellBranchCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        allowParalellBranchCheckBox.setSelected(true);
        allowParalellBranchCheckBox.setText("Allow paralell branches");
        allowParalellBranchCheckBox.setName("allowParalellBranchCheckBox");
        add(allowParalellBranchCheckBox);

        adjustmentCheckBox.setFont(new java.awt.Font("Dialog", 0, 12));
        adjustmentCheckBox.setSelected(true);
        adjustmentCheckBox.setText("Include adjustments/Controls");
        adjustmentCheckBox.setName("adjustmentCheckBox");
        add(adjustmentCheckBox);

    }
    // </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adjustmentCheckBox;
    private javax.swing.JCheckBox allowParalellBranchCheckBox;
    // End of variables declaration//GEN-END:variables
    
}
