 /*
  * @(#)MachStateSelDialog.java   
  *
  * Copyright (C) 2006 www.interpss.org
  *
  * This program is free software; you can redistribute it and/or
  * modify it under the terms of the GNU LESSER GENERAL PUBLIC LICENSE
  * as published by the Free Software Foundation; either version 2.1
  * of the License, or (at your option) any later version.
  *
  * This program is distributed in the hope that it will be useful,
  * but WITHOUT ANY WARRANTY; without even the implied warranty of
  * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  * GNU General Public License for more details.
  *
  * @Author Mike Zhou
  * @Version 1.0
  * @Date 09/15/2006
  * 
  *   Revision History
  *   ================
  *
  */

package org.interpss.editor.ui.chart;

import java.util.List;

import com.interpss.common.SpringAppContext;
import com.interpss.common.io.IProjectDataManager;
import com.interpss.common.io.ISimuRecManager;
import com.interpss.common.ui.WinUtilities;
import com.interpss.common.util.IpssLogger;

/**
 *
 * @author  mzhou
 */
public class DStabPlotSelectionDialog extends javax.swing.JDialog {
    private int caseId = 0;
    
    /** Creates new form MachStateSelDialog */
    public DStabPlotSelectionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        WinUtilities.center(this);
        this.setVisible(true);
    }

    public void init(int aCaseId) {
    	/*
		ISimuRecManager simuRecManager = SpringAppContext.getSimuRecManager();
        this.caseId = aCaseId;
	  	List list = null;
	  	try {
	  		simuRecManager.getElemIdStrList(this.caseId, ISimuRecManager.REC_TYPE_DStabMachineStates, IProjectDataManager.CaseType_DStabSimuRec);
	  	} catch (Exception e) {
	  		IpssLogger.logErr(e);
	  		SpringAppContext.getEditorDialogUtil().showErrMsgDialog("Error to get mach list from DB", 
	  				e.toString() + "\nPlease contact InterPSS support");
	  	}
		if (list != null) {
//			this.machListComboBox.setModel(new javax.swing.DefaultComboBoxModel(list.toArray()));
		    //setStateComboList((String)this.machListComboBox.getSelectedItem());
		}
		*/
    }
    
    private void setStateComboList(String machId) {
    	IpssLogger.getLogger().info("setStateComboList for machId: " + machId);
//		this.machStateComboBox.setModel(new javax.swing.DefaultComboBoxModel(
//				ChartManager.getStatesNameList(this.caseId, machId, ISimuRecManager.REC_TYPE_DStabMachineStates)));
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        typeButtonGroup = new javax.swing.ButtonGroup();
        typeSelectPanel = new javax.swing.JPanel();
        allRadioButton = new javax.swing.JRadioButton();
        machRadioButton = new javax.swing.JRadioButton();
        busRadioButton = new javax.swing.JRadioButton();
        busDeviceRadioButton = new javax.swing.JRadioButton();
        branchRadioButton = new javax.swing.JRadioButton();
        branchDeviceRadioButton = new javax.swing.JRadioButton();
        itemSelectPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        itemSelectList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        stateSelectList = new javax.swing.JList();
        closeButton = new javax.swing.JButton();
        plotButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transient Stability Simulation Plotting Dialog");
        typeButtonGroup.add(allRadioButton);
        allRadioButton.setText("All");
        allRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        allRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        typeButtonGroup.add(machRadioButton);
        machRadioButton.setText("Machine");
        machRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        machRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        machRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                machRadioButtonActionPerformed(evt);
            }
        });

        typeButtonGroup.add(busRadioButton);
        busRadioButton.setText("Bus");
        busRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        busRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        typeButtonGroup.add(busDeviceRadioButton);
        busDeviceRadioButton.setText("Dynamic Bus Device");
        busDeviceRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        busDeviceRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        typeButtonGroup.add(branchRadioButton);
        branchRadioButton.setText("Branch");
        branchRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        branchRadioButton.setEnabled(false);
        branchRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        typeButtonGroup.add(branchDeviceRadioButton);
        branchDeviceRadioButton.setText("Dynamic Branch Device");
        branchDeviceRadioButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        branchDeviceRadioButton.setEnabled(false);
        branchDeviceRadioButton.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout typeSelectPanelLayout = new org.jdesktop.layout.GroupLayout(typeSelectPanel);
        typeSelectPanel.setLayout(typeSelectPanelLayout);
        typeSelectPanelLayout.setHorizontalGroup(
            typeSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(typeSelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(allRadioButton)
                .add(16, 16, 16)
                .add(machRadioButton)
                .add(19, 19, 19)
                .add(busRadioButton)
                .add(15, 15, 15)
                .add(busDeviceRadioButton)
                .add(25, 25, 25)
                .add(branchRadioButton)
                .add(23, 23, 23)
                .add(branchDeviceRadioButton)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        typeSelectPanelLayout.setVerticalGroup(
            typeSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(typeSelectPanelLayout.createSequentialGroup()
                .add(24, 24, 24)
                .add(typeSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(allRadioButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(machRadioButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(busRadioButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(busDeviceRadioButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(typeSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(branchRadioButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(branchDeviceRadioButton, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        itemSelectList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        itemSelectList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                itemSelectListValueChanged(evt);
            }
        });

        jScrollPane1.setViewportView(itemSelectList);

        stateSelectList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        stateSelectList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                stateSelectListValueChanged(evt);
            }
        });

        jScrollPane2.setViewportView(stateSelectList);

        org.jdesktop.layout.GroupLayout itemSelectPanelLayout = new org.jdesktop.layout.GroupLayout(itemSelectPanel);
        itemSelectPanel.setLayout(itemSelectPanelLayout);
        itemSelectPanelLayout.setHorizontalGroup(
            itemSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(itemSelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 136, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 322, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        itemSelectPanelLayout.setVerticalGroup(
            itemSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, itemSelectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(itemSelectPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
                .addContainerGap())
        );

        closeButton.setText("  Close  ");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        plotButton.setText("    Plot   ");
        plotButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plotButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, typeSelectPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, itemSelectPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(layout.createSequentialGroup()
                        .add(175, 175, 175)
                        .add(plotButton)
                        .add(49, 49, 49)
                        .add(closeButton)))
                .addContainerGap())
        );

        layout.linkSize(new java.awt.Component[] {closeButton, plotButton}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(typeSelectPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(itemSelectPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(closeButton)
                    .add(plotButton))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stateSelectListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_stateSelectListValueChanged
// TODO add your handling code here:
    }//GEN-LAST:event_stateSelectListValueChanged

    private void itemSelectListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_itemSelectListValueChanged
// TODO add your handling code here:
    }//GEN-LAST:event_itemSelectListValueChanged

    private void machRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_machRadioButtonActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_machRadioButtonActionPerformed

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void plotButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plotButtonActionPerformed
    	if (machRadioButton.isSelected()) {
//    		String state = (String)machStateComboBox.getSelectedItem();
//    		String machId = (String)this.machListComboBox.getSelectedItem();
//    		ChartManager.plotStateCurve(this.caseId, machId, state, "Not defined", ISimuRecManager.REC_TYPE_DStabMachineStates);
    	}
    }//GEN-LAST:event_plotButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DStabPlotSelectionDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton allRadioButton;
    private javax.swing.JRadioButton branchDeviceRadioButton;
    private javax.swing.JRadioButton branchRadioButton;
    private javax.swing.JRadioButton busDeviceRadioButton;
    private javax.swing.JRadioButton busRadioButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JList itemSelectList;
    private javax.swing.JPanel itemSelectPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton machRadioButton;
    private javax.swing.JButton plotButton;
    private javax.swing.JList stateSelectList;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JPanel typeSelectPanel;
    // End of variables declaration//GEN-END:variables
    
}
